### ISSUE TITLE
Renaming SignageAndTraffic

### ISSUE THREAD

**Issue by daseinkapital** [GeoguessrTools/calico-cut-pants#8]
To the extent that signage and traffic category contains roadlines, I think we should refer to it as something like SignsRoadsAndTraffic or something.

And then to a further extent, I think driving side belongs in this category potentially. Easily persuaded away from the latter.

Finally, we should have a key for RoadQuality (this will probably be ImageWithDescription (unknown if it would be a list)) because I know Texas roads apparently have very distinguished concrete, certain European countries have trash roads, and certain dirt roads (*ahem* Brazil *ahem*) are probably worthy of noting. If you think some amount of this info should be broken out, I'm also amenable to that (there is arguably enough info on signs, roads, and traffic to constitute each as their own category).

**Comment by TheConcierge** [comment]
> (_ahem_ Brazil _ahem_) 

BRAZILIAN DIRT BRAZILIAN DIRT
